[package]
name = "rust_gtk3_example"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/smallB007/rust_gtk3_example.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.4"
